name: isort-command
on:
  repository_dispatch:
    types: [isort-command]
jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      # Checkout the pull request branch
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      # Setup Python environment
      - uses: actions/setup-python@v1

      # Install isort
      - name: Install isort
        run: pip install -U "isort>=5.1"

      # Execute isort in check mode
      - name: isort
        id: isort
        run: echo ::set-output name=format::$(isort --check --quiet . || echo "true")

      # Execute isort and commit the change to the PR branch
      - name: Commit to the PR branch
        if: steps.isort.outputs.format == 'true'
        run: |
          isort .
          git config --global user.name 'yt-fido'
          git config --global user.email 'yt.fido@gmail.com'
          git commit -am "[isort-command] fixes"
          git push

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
